config/routes.rb
Rails.application.routes.draw do
  resources :listings
  #get 'home/index'
  root 'listings#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:buysell, :product, :price, :contacts, :description, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Ruby Demo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to "All Listings", listings_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Add Listing", new_listing_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Homeindex</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Listings</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>

    <%= render 'home/navbar' %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/listings/_form.html.erb
<div class = "container-fluid">
  <%= form_with(model: listing) do |form| %>
    <% if listing.errors.any? %>
      <div style="color: red"">
        <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

        <ul>
          <% listing.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :Buying_or_selling?, style: "display: block" %>
      <%= form.text_field :buysell %>
    </div>

    <div class="form-group">
      <%= form.label :product, style: "display: block" %>
      <%= form.text_field :product %>
    </div>

    <div class="form-group">
      <%= form.label :price, style: "display: block" %>
      <%= form.text_field :price %>
    </div>

    <div class="form-group">
      <%= form.label :contacts, style: "display: block" %>
      <%= form.text_field :contacts %>
    </div>

    <div class="form-group">
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description %>
    </div>

    <div class="form-group">
      <%= form.label :Shipping_or_Local?, style: "display: block" %>
      <%= form.text_field :password %>
    </div>

    <div class="form-group">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/listings/_listing.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
    <h1 class="display-4"><%= listing.product %></h1>
    <p class="lead">
      <div id="<%= dom_id listing %>">
      <p>
        <strong>Buy or Sell:</strong>
        <%= listing.buysell %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= listing.price %>
      </p>

      <p>
        <strong>Contacts:</strong>
        <%= listing.contacts %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= listing.description %>
      </p>

      <p>
        <strong>Shipping or Local:</strong>
        <%= listing.password %>
      </p>
      <%= link_to "Edit", edit_listing_path(@listing), class:"btn btn-secondary" %>
      <%= link_to "Back", listings_path, class:"btn btn-dark" %> <br/> <br/>
      <%= button_to 'Delete', @listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      </div>
    </p>
  </div>
</div>

<p style="color: green"><%= notice %></p>

app/views/listings/edit.html.erb
<div class = "container-fluid">
  <h1>Editing listing</h1>
</div>

<%= render "form", listing: @listing %>

<br>

<div class = "container-fluid">
  <%= link_to "Show this listing", @listing %> |
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container-fluid">
  <h1>Listings</h1>

  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th scope="col">Type</th>
        <th scope="col">Product</th>
        <th scope="col">Price</th>
        <th scope="col">Contacts</th>
        <th scope="col">Description</th>
        <th scope="col">Link</th>
      </tr>
    </thead>


      <tbody>
      <% @listings.each do |listing| %>
        <tr>
        <td> <%= listing.buysell %> </td>
        <td> <%= listing.product %> </td>
        <td> <%= listing.price %> </td>
        <td> <%= listing.contacts %> </td>
        <td> <%= listing.description %> </td>
        <td> <%= link_to "Show this listing", listing%></td>
        </tr>
      <% end %>
      </tbody>
  </table>
  <%= link_to "New listing", new_listing_path, class:"btn btn-dark" %>
</div>

app/views/listings/new.html.erb
<div class = "container-fluid">
  <h1>New Listing</h1>
</div>

<%= render "form", listing: @listing %>

<br>

<div class="container-fluid">
  <%= link_to "Back to listings", listings_path %>
</div>

app/views/listings/show.html.erb
<%= render @listing %>